/* BOTS */
// Create
export const BOTS_NEW_REQUEST = 'BOTS_NEW_REQUEST';
export const BOTS_NEW_SUCCESS = 'BOTS_NEW_SUCCESS';
export const BOTS_NEW_FAILURE = 'BOTS_NEW_FAILURE';
// Read
export const BOTS_REQUEST = 'BOTS_REQUEST';
export const BOTS_SUCCESS = 'BOTS_SUCCESS';
export const BOTS_FAILURE = 'BOTS_FAILURE';
// Update
export const BOTS_UPDATE_REQUEST = 'BOTS_UPDATE_REQUEST';
export const BOTS_UPDATE_SUCCESS = 'BOTS_UPDATE_SUCCESS';
export const BOTS_UPDATE_FAILURE = 'BOTS_UPDATE_FAILURE';
// Delete
export const BOTS_DEL_REQUEST = 'BOTS_DEL_REQUEST';
export const BOTS_DEL_SUCCESS = 'BOTS_DEL_SUCCESS';
export const BOTS_DEL_FAILURE = 'BOTS_DEL_FAILURE';
