/* GRAPHS */
// Read
export const GRAPHS_REQUEST = 'GRAPHS_REQUEST';
export const GRAPHS_SUCCESS = 'GRAPHS_SUCCESS';
export const GRAPHS_FAILURE = 'GRAPHS_FAILURE';

// Update
export const GRAPHS_UPDATE_REQUEST = 'GRAPHS_UPDATE_REQUEST';
export const GRAPHS_UPDATE_SUCCESS = 'GRAPHS_UPDATE_SUCCESS';
export const GRAPHS_UPDATE_FAILURE = 'GRAPHS_UPDATE_FAILURE';

// Position
export const GRAPHS_DROP_REQUEST = 'GRAPHS_DROP_REQUEST';
export const GRAPHS_DROP_STORE = 'GRAPHS_DROP_STORE';
export const GRAPHS_DROP_SUCCESS = 'GRAPHS_DROP_SUCCESS';
export const GRAPHS_DROP_FAILURE = 'GRAPHS_DROP_FAILURE';

// Reset
export const GRAPHS_RESET = 'GRAPHS_RESET';
