/* INSTANCES */
// Create
export const INSTANCES_NEW_REQUEST = 'INSTANCES_NEW_REQUEST';
export const INSTANCES_NEW_SUCCESS = 'INSTANCES_NEW_SUCCESS';
export const INSTANCES_NEW_FAILURE = 'INSTANCES_NEW_FAILURE';
// Read
export const INSTANCES_REQUEST = 'INSTANCES_REQUEST';
export const INSTANCES_SUCCESS = 'INSTANCES_SUCCESS';
export const INSTANCES_FAILURE = 'INSTANCES_FAILURE';
// Update
export const INSTANCES_UPDATE_REQUEST = 'INSTANCES_UPDATE_REQUEST';
export const INSTANCES_UPDATE_SUCCESS = 'INSTANCES_UPDATE_SUCCESS';
export const INSTANCES_UPDATE_FAILURE = 'INSTANCES_UPDATE_FAILURE';
// Delete
export const INSTANCES_DEL_REQUEST = 'INSTANCES_DEL_REQUEST';
export const INSTANCES_DEL_SUCCESS = 'INSTANCES_DEL_SUCCESS';
export const INSTANCES_DEL_FAILURE = 'INSTANCES_DEL_FAILURE';
// Reset
export const INSTANCES_RESET = 'INSTANCES_RESET';
