/* INSTANCES */
// Create
export const INSTANCES_PARAM_NEW_REQUEST = 'INSTANCES_PARAM_NEW_REQUEST';
export const INSTANCES_PARAM_NEW_SUCCESS = 'INSTANCES_PARAM_NEW_SUCCESS';
export const INSTANCES_PARAM_NEW_FAILURE = 'INSTANCES_PARAM_NEW_FAILURE';
// Read
export const INSTANCES_PARAM_REQUEST = 'INSTANCES_PARAM_REQUEST';
export const INSTANCES_PARAM_SUCCESS = 'INSTANCES_PARAM_SUCCESS';
export const INSTANCES_PARAM_FAILURE = 'INSTANCES_PARAM_FAILURE';
// Update
export const INSTANCES_PARAM_UPDATE_REQUEST = 'INSTANCES_PARAM_UPDATE_REQUEST';
export const INSTANCES_PARAM_UPDATE_SUCCESS = 'INSTANCES_PARAM_UPDATE_SUCCESS';
export const INSTANCES_PARAM_UPDATE_FAILURE = 'INSTANCES_PARAM_UPDATE_FAILURE';
// Delete
export const INSTANCES_PARAM_DEL_REQUEST = 'INSTANCES_PARAM_DEL_REQUEST';
export const INSTANCES_PARAM_DEL_SUCCESS = 'INSTANCES_PARAM_DEL_SUCCESS';
export const INSTANCES_PARAM_DEL_FAILURE = 'INSTANCES_PARAM_DEL_FAILURE';
// Reset
export const INSTANCES_PARAM_RESET = 'INSTANCES_PARAM_RESET';
