/* INSTANCES */
// Create
export const INSTANCES_PARAMETERS_NEW_REQUEST = 'INSTANCES_PARAMETERS_NEW_REQUEST';
export const INSTANCES_PARAMETERS_NEW_SUCCESS = 'INSTANCES_PARAMETERS_NEW_SUCCESS';
export const INSTANCES_PARAMETERS_NEW_FAILURE = 'INSTANCES_PARAMETERS_NEW_FAILURE';
// Read
export const INSTANCES_PARAMETERS_REQUEST = 'INSTANCES_PARAMETERS_REQUEST';
export const INSTANCES_PARAMETERS_REQUEST_BY_INSTANCE = 'INSTANCES_PARAMETERS_REQUEST_BY_INSTANCE';
export const INSTANCES_PARAMETERS_SUCCESS = 'INSTANCES_PARAMETERS_SUCCESS';
export const INSTANCES_PARAMETERS_FAILURE = 'INSTANCES_PARAMETERS_FAILURE';
// Update
export const INSTANCES_PARAMETERS_UPDATE_REQUEST = 'INSTANCES_PARAMETERS_UPDATE_REQUEST';
export const INSTANCES_PARAMETERS_UPDATE_SUCCESS = 'INSTANCES_PARAMETERS_UPDATE_SUCCESS';
export const INSTANCES_PARAMETERS_UPDATE_FAILURE = 'INSTANCES_PARAMETERS_UPDATE_FAILURE';
// Delete
export const INSTANCES_PARAMETERS_DEL_REQUEST = 'INSTANCES_PARAMETERS_DEL_REQUEST';
export const INSTANCES_PARAMETERS_DEL_SUCCESS = 'INSTANCES_PARAMETERS_DEL_SUCCESS';
export const INSTANCES_PARAMETERS_DEL_FAILURE = 'INSTANCES_PARAMETERS_DEL_FAILURE';
// Reset
export const INSTANCES_PARAMETERS_RESET = 'INSTANCES_PARAMETERS_RESET';
