/* INSTANCES */
// Create
export const MODULES_NEW_REQUEST = 'MODULES_NEW_REQUEST';
export const MODULES_NEW_SUCCESS = 'MODULES_NEW_SUCCESS';
export const MODULES_NEW_FAILURE = 'MODULES_NEW_FAILURE';
// Read
export const MODULES_REQUEST = 'MODULES_REQUEST';
export const MODULES_SUCCESS = 'MODULES_SUCCESS';
export const MODULES_FAILURE = 'MODULES_FAILURE';
// Update
export const MODULES_UPDATE_REQUEST = 'MODULES_UPDATE_REQUEST';
export const MODULES_UPDATE_SUCCESS = 'MODULES_UPDATE_SUCCESS';
export const MODULES_UPDATE_FAILURE = 'MODULES_UPDATE_FAILURE';
// Delete
export const MODULES_DEL_REQUEST = 'MODULES_DEL_REQUEST';
export const MODULES_DEL_SUCCESS = 'MODULES_DEL_SUCCESS';
export const MODULES_DEL_FAILURE = 'MODULES_DEL_FAILURE';
// Reset
export const MODULES_RESET = 'MODULES_RESET';
