/* ROOMS */
// Create
export const ROOMS_NEW_REQUEST = 'ROOMS_NEW_REQUEST';
export const ROOMS_NEW_SUCCESS = 'ROOMS_NEW_SUCCESS';
export const ROOMS_NEW_FAILURE = 'ROOMS_NEW_FAILURE';
// Read
export const ROOMS_REQUEST = 'ROOMS_REQUEST';
export const ROOMS_SUCCESS = 'ROOMS_SUCCESS';
export const ROOMS_FAILURE = 'ROOMS_FAILURE';
// Update
export const ROOMS_UPDATE_REQUEST = 'ROOMS_UPDATE_REQUEST';
export const ROOMS_UPDATE_SUCCESS = 'ROOMS_UPDATE_SUCCESS';
export const ROOMS_UPDATE_FAILURE = 'ROOMS_UPDATE_FAILURE';
// Delete
export const ROOMS_DEL_REQUEST = 'ROOMS_DEL_REQUEST';
export const ROOMS_DEL_SUCCESS = 'ROOMS_DEL_SUCCESS';
export const ROOMS_DEL_FAILURE = 'ROOMS_DEL_FAILURE';
