/* INSTANCES */
// Create
export const TEMPLATES_NEW_REQUEST = 'TEMPLATES_NEW_REQUEST';
export const TEMPLATES_NEW_SUCCESS = 'TEMPLATES_NEW_SUCCESS';
export const TEMPLATES_NEW_FAILURE = 'TEMPLATES_NEW_FAILURE';
// Read
export const TEMPLATES_REQUEST = 'TEMPLATES_REQUEST';
export const TEMPLATES_SUCCESS = 'TEMPLATES_SUCCESS';
export const TEMPLATES_FAILURE = 'TEMPLATES_FAILURE';
// Update
export const TEMPLATES_UPDATE_REQUEST = 'TEMPLATES_UPDATE_REQUEST';
export const TEMPLATES_UPDATE_SUCCESS = 'TEMPLATES_UPDATE_SUCCESS';
export const TEMPLATES_UPDATE_FAILURE = 'TEMPLATES_UPDATE_FAILURE';
// Delete
export const TEMPLATES_DEL_REQUEST = 'TEMPLATES_DEL_REQUEST';
export const TEMPLATES_DEL_SUCCESS = 'TEMPLATES_DEL_SUCCESS';
export const TEMPLATES_DEL_FAILURE = 'TEMPLATES_DEL_FAILURE';
// Reset
export const TEMPLATES_RESET = 'TEMPLATES_RESET';
